# testbench
test_top.v
dram.v

# netlist generated by Design Compiler
../syn/netlist/lenet_syn.v

# Logic Gate models
-v /usr/cadtool/cad/synopsys/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

+define+GATESIM
+access+r
