# testbench
test_dram.v
dram.v

# netlist generated by ICC
../icc/post_layout/CHIP_layout.v

# Logic Gate models
-v /usr/cadtool/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

+define+POSTSIM
+access+r